# wedisDB configuration
# Case insensitive, but use Camel Case naming
# notice: if don't config item, use defualt item's value
[server]
logLevel = "debug"
projectName = "wedisSrv"

# http Server listen address, set empty to disable
httpAddr = "127.0.0.1:8110"

# oltp cllector grpc endpoint address, set empty to disable
oltpCollectorGrpcEndpoint = "0.0.0.0:4317"

# storager name default xdis-storager 
# xdis-storager local storager with openkv
# xdis-tikv remote rpc storager with tikv
storagerName = "xdis-storager"

[server.respCmdSrv]
# resp cmd Server listen address
addr = "0.0.0.0:6666"

# auth password
authPassword = ""

# if connection receives no data after n seconds, it may be dead, close
# 0 to disable and not check
# idle conn close time (s)
connKeepaliveInterval = 0

# resp cmd Server mode
# standalone 
# replica (doing) classic mode, need proxy manage sharding like codis
# replica (doing) single raft mode like redis raft, need proxy manage sharding like codis
# https://jepsen.io/analyses/redis-raft-1b3fbf6
# tikv (doing2test) + pd, support gloabal txn
# matrix (todo) multi raft group
# cluster (todo) like redis cluster mode
# AI mind? just YY, try
mode = "standalone"


[storeCfg]
# Data store path, all wedisdb's data will be saved here
dataDir = "./data"

# Set the number of databases. You can use `select dbindex` to choose a db.
# dbindex must be in [0, databases - 1].
# Default databases is 16, maximum is 10240 now.
databases = 16

# Sync commit to disk if possible
#  0: no sync
#  1: sync every second
#  2: sync every commit
dbSyncCommit = 0

# checking TTL (time to live) data every n seconds
# if you set big, the expired data may not be deleted immediately
ttlCheckInterval = 1

# Choose which backend storage to use, 
# impl openkv driver register to support:
kvStoreName = "goleveldb"

# If not set, use dataDir/"kvStoreName"_data
dbPath = ""

[goLeveldbCfg]
# if true, compression use snappy 
compression = false
block_size = 32768
write_buffer_size = 67108864
cache_size = 524288000
max_open_files = 1024


[tikvStoreCfg]
prefixKey = "hitiki"
Databases = 16
ttlCheckInterval = 1

[tikvStoreCfg.tikvClientOpts]
useTxnApi = 1
pdAddrs = "127.0.0.1:2379"
useAsyncCommit=0
tryOnePcCommit=0
usePessimisticTxn=0

[tikvStoreCfg.gcJobOpts]
gcEnabled = 1
gcInterval = 600
gcConcurrency = 8
gcSafepointLifeTime = 600

[tikvStoreCfg.leaderJobOpts]
leaderCheckInterval = 30
leaderLeaseDuration = 60
