# wedisDB configuration
# Case insensitive, but use Camel Case naming
# notice: if don't config item, use defualt item's value
[server]
logLevel = "debug"
projectName = "wedisSrv"

# http Server listen address, set empty to disable
httpAddr = "127.0.0.1:8110"

# oltp cllector grpc endpoint address, set empty to disable
oltpCollectorGrpcEndpoint = "0.0.0.0:4317"

# use store type, 
# local, rpc(dist kv store eg:tikv)
# default local
storeType = "local"


[server.respCmdSrv]
# resp cmd Server listen address
addr = "0.0.0.0:6666"

# auth password
authPassword = ""

# if connection receives no data after n seconds, it may be dead, close
# 0 to disable and not check
# idle conn close time (s)
connKeepaliveInterval = 0

# resp cmd Server mode
# standalone (doing2test)
# replica (doing) classic mode, need proxy manage sharding like codis
# tikv (doing2test)
# matrix (todo)
mode = "standalone"


[server.storeOpts]
# Data store path, all wedisdb's data will be saved here
dataDir = "./data"

# Set the number of databases. You can use `select dbindex` to choose a db.
# dbindex must be in [0, databases - 1].
# Default databases is 16, maximum is 10240 now.
databases = 16

# Sync commit to disk if possible
#  0: no sync
#  1: sync every second
#  2: sync every commit
dbSyncCommit = 0

# checking TTL (time to live) data every n seconds
# if you set big, the expired data may not be deleted immediately
ttlCheckInterval = 1

# Choose which backend storage to use, 
# impl openkv driver register to support:
kvStoreName = "goleveldb"

# If not set, use dataDir/"kvStoreName"_data
dbPath = ""


[server.storeOpts.goLeveldbCfg]
# if true, compression use snappy 
compression = false
block_size = 32768
write_buffer_size = 67108864
cache_size = 524288000
max_open_files = 1024
