# wedisDB configuration
# Case insensitive, but use Camel Case naming
# notice: if don't config item, use defualt item's value

# storager name default xdis-storager 
# xdis-storager local storager with openkv
# xdis-tikv remote rpc storager with tikv 
#   tikv + pd,multi raft group, support gloabal dist txn (keys from diff region) (cp)
storagerName = "xdis-storager"

# resp cmd Server mode name
# standalone 
# replica-master-slave classic mode, need proxy manage sharding like codis (ap)
# replica-single-raft mode like redis raft, need proxy manage sharding like codis (cp)
# replica-multi-raft mode, need placemet driver (cp)
# https://jepsen.io/analyses/redis-raft-1b3fbf6
# matrix (todo) multi raft group (cp)
# cluster (todo) like redis cluster mode (ap)
respCmdSrvName = "standalone"
#respCmdSrvName = "replica-master-slave"


server.logLevel = "debug"
server.projectName = "wedisSrv"

# http Server listen address, set empty to disable
server.httpAddr = "127.0.0.1:8110"

# oltp cllector grpc endpoint address, set empty to disable
#server.oltpCollectorGrpcEndpoint = "0.0.0.0:4317"


# resp cmd Server listen address
standaloneRespCmdSrvCfg.addr = "0.0.0.0:6666"

# auth password
standaloneRespCmdSrvCfg.authPassword = ""

# if connection receives no data after n seconds, it may be dead, close
# 0 to disable and not check
# idle conn close time (s)
standaloneRespCmdSrvCfg.connKeepaliveInterval = 0


# Data store path, all wedisdb's data will be saved here
storeCfg.dataDir = "./data"

# Set the number of databases. You can use `select dbindex` to choose a db.
# dbindex must be in [0, databases - 1].
# Default databases is 16, maximum is 10240 now.
storeCfg.databases = 16

# Sync commit to disk if possible
#  0: no sync
#  1: sync every second
#  2: sync every commit
storeCfg.dbSyncCommit = 0

# checking TTL (time to live) data every n seconds
# if you set big, the expired data may not be deleted immediately
storeCfg.ttlCheckInterval = 1

# Choose which backend storage to use, 
# impl openkv driver register to support:
storeCfg.kvStoreName = "goleveldb"

# If not set, use dataDir/"kvStoreName"_data
storeCfg.dbPath = ""


# if true, compression use snappy 
goLeveldbCfg.compression = false
goLeveldbCfg.blockSize = 32768
goLeveldbCfg.writeBufferSize = 67108864
goLeveldbCfg.cacheSize = 524288000
goLeveldbCfg.maxOpenFiles = 1024
goLeveldbCfg.compactionTableSize = 33554432
goLeveldbCfg.writeL0SlowdownTrigger = 16
goLeveldbCfg.writeL0PauseTrigger = 64


tikvStoreCfg.prefixKey = "hitiki"
tikvStoreCfg.Databases = 16
tikvStoreCfg.ttlCheckInterval = "1"

tikvStoreCfg.tikvClientOpts.useTxnApi = 1
tikvStoreCfg.tikvClientOpts.pdAddrs = "127.0.0.1:2379"
tikvStoreCfg.tikvClientOpts.useAsyncCommit = 0
tikvStoreCfg.tikvClientOpts.tryOnePcCommit = 0
tikvStoreCfg.tikvClientOpts.usePessimisticTxn = 0

tikvStoreCfg.gcJobOpts.gcEnabled = 1
tikvStoreCfg.gcJobOpts.gcInterval = 600
tikvStoreCfg.gcJobOpts.gcConcurrency = 8
tikvStoreCfg.gcJobOpts.gcSafepointLifeTime = 600

tikvStoreCfg.leaderJobOpts.leaderCheckInterval = 30
tikvStoreCfg.leaderJobOpts.leaderLeaseDuration = 60
