// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package srv

import (
	"context"
	"github.com/tidwall/redcon"
	"github.com/weedge/wedis/internal/srv/config"
	"github.com/weedge/wedis/pkg/configparser"
	"github.com/weedge/wedis/pkg/utils/logutils"
)

// Injectors from wire.go:

// NewServer build server with wire, dependency obj inject, so init random
func NewServer(ctx context.Context) (*Server, error) {
	provider := configparser.Default()
	options, err := config.Configure(provider)
	if err != nil {
		return nil, err
	}
	serverOptions := options.Server
	level := serverOptions.LogLevel
	v := serverOptions.LogMeta
	iKitexZapKVLogger := logutils.NewkitexZapKVLogger(level, v)
	serveMux := redcon.NewServeMux()
	server := &Server{
		opts:          serverOptions,
		kitexKVLogger: iKitexZapKVLogger,
		mux:           serveMux,
	}
	return server, nil
}
