// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package srv

import (
	"context"
	"github.com/weedge/openkv-goleveldb"
	"github.com/weedge/pkg/configparser"
	"github.com/weedge/pkg/driver"
	driver2 "github.com/weedge/pkg/driver/openkv"
	"github.com/weedge/pkg/utils/logutils"
	"github.com/weedge/wedis/internal/srv/config"
	"github.com/weedge/xdis-replica-storager"
	"github.com/weedge/xdis-standalone"
	"github.com/weedge/xdis-storager"
	"github.com/weedge/xdis-tikv"
)

// Injectors from wire.go:

// ParserCfg config paser
func ParserCfg() (*config.Options, error) {
	provider := configparser.Default()
	options, err := config.Configure(provider)
	if err != nil {
		return nil, err
	}
	return options, nil
}

// NewServer server init
func NewServer(contextContext context.Context, options *config.Options) (*Server, error) {
	serverOptions := &options.Server
	level := serverOptions.LogLevel
	v := serverOptions.LogMeta
	iKitexZapKVLogger := logutils.NewkitexZapKVLogger(level, v)
	respServiceName := options.RespCmdSrvName
	iRespService, err := driver.GetRespCmdSrv(respServiceName)
	if err != nil {
		return nil, err
	}
	string2 := options.StoragerName
	iStorager, err := driver.GetStorager(string2)
	if err != nil {
		return nil, err
	}
	server := &Server{
		opts:          serverOptions,
		kitexKVLogger: iKitexZapKVLogger,
		respSrv:       iRespService,
		store:         iStorager,
	}
	return server, nil
}

func RegisterStandaloneRespCmdSrv(options *config.Options) error {
	respCmdServiceOptions := &options.StandaloneRespCmdSrvCfg
	respCmdService := standalone.New(respCmdServiceOptions)
	error2 := driver.RegisterRespCmdSrv(respCmdService)
	return error2
}

func RegisterReplicaMasterSlaveRespCmdSrv(options *config.Options) error {
	respCmdServiceOptions := &options.RplMasterSlaveRespCmdSrvCfg
	configRespCmdServiceOptions := &options.StandaloneRespCmdSrvCfg
	respCmdService := replica.New(respCmdServiceOptions, configRespCmdServiceOptions)
	error2 := driver.RegisterRespCmdSrv(respCmdService)
	return error2
}

// RegisterXdisStorager register storager xdis-storager
func RegisterXdisStorager(options *config.Options) error {
	storgerOptions := &options.StoreCfg
	storagerStorager := storager.New(storgerOptions)
	error2 := driver.RegisterStorager(storagerStorager)
	return error2
}

// RegisterXdisTikv register storager xdis-tikv
func RegisterXdisTikv(options *config.Options) error {
	storagerOptions := &options.TikvCfg
	xdistikvStorager := xdistikv.New(storagerOptions)
	error2 := driver.RegisterStorager(xdistikvStorager)
	return error2
}

// RegisterGoleveldb register kv store engine goleveldb
func RegisterGoleveldb(options *config.Options) error {
	storeType := _wireStoreTypeValue
	levelDBConfig := options.GoLeveldbCfg
	option := goleveldb.WithConfig(levelDBConfig)
	v := ProvideOpts(option)
	store := goleveldb.New(storeType, v...)
	error2 := driver2.Register(store)
	return error2
}

var (
	_wireStoreTypeValue = goleveldb.StoreTypeDB
)

// RegisterMemGoleveldb regisiter kv store engine memory goleveldb
func RegisterMemGoleveldb(options *config.Options) error {
	storeType := _wireGoleveldbStoreTypeValue
	levelDBConfig := options.GoLeveldbCfg
	option := goleveldb.WithConfig(levelDBConfig)
	v := ProvideOpts(option)
	store := goleveldb.New(storeType, v...)
	error2 := driver2.Register(store)
	return error2
}

var (
	_wireGoleveldbStoreTypeValue = goleveldb.StoreTypeMemory
)

// wire.go:

func ProvideOpts(
	c goleveldb.Option,
) []goleveldb.Option {
	return []goleveldb.Option{
		c,
	}
}
